---
title: "lab09-yvonne-zhou"
author: "Yvonne Zhou"
date: "4/4/2019"
output: html_document
---

```{r}
library(testthat)
```

#2)
```{r}
head(USArrests)
```

```{r}
states <- rownames(USArrests)
head(states)
```

```{r}
num_chars <- nchar(states)
char_freqs = table(num_chars)
char_freqs = data.frame(char_freqs)
char_freqs
barplot(char_freqs$Freq)
```

```{r}
paste('Pumpkin', 'Pie')
```
###paste()
```{r}
paste_result = paste(states, num_chars, sep = " = ")
paste_result
```

```{r}
first_five = head(states, 5)
first_five = paste(first_five, collapse = "")
first_five
```

###Permutations
```{r}
factorial(7)/factorial(3)
```

```{r}
shortened_states_first = substr(states, 1, 3)
shortened_states_first
```

```{r}
shortened_states_last = substr(states, num_chars - 2, num_chars)
shortened_states_last
```

```{r}
first_and_last_three = paste0(substr(states, 1, 1), shortened_states_last)
first_and_last_three
```

```{r}
result = list()
for (i in 1:max(num_chars)) {
  name = paste0(i, "-chars")
  value = paste(states[num_chars == i], collapse = ", ")
  if (i %% 2 == 0) {
    value = toupper(value)
  }
  if (i %% 2 == 1) {
    value = tolower(value)
  }
  if (value != "") {
    result[[name]] <- value
  }
}
result
```

###Converting Temperatures
```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}
```

```{r}
temp_convert <- function(x = 1, to = "celsius") {
  to  = tolower(to)
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
```

```{r}
temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

###Names of files
```{r}
# vector of file names
#1. using for loop
result1 = c()
for (i in 1:10) {
  result1 = append(result1, paste0(paste0("file", i), ".csv"))
}
result1
#2. using 1:10
result2 = paste0(paste0("file", 1:10), ".csv")
result2
#3. using seq(1, 10, 1)
result3 = paste0(paste0("file", seq(1, 10, 1)), ".csv")
result3


# rename vector of file names
result_renamed = substr(result1, 5, nchar(result1))
result_renamed = paste0("dataset", result_renamed)
result_renamed
```

###cat()
```{r}
# name of output file
outfile <- "output.txt"

# modified
cat('---\ntitle: "Some title"\nauthor: "Your name"\n', file = outfile)
cat('date: "today\'s date"', file = outfile, append = TRUE)
cat("\noutput: html_document\n---\n\n", file = outfile, append = TRUE)

# writing to 'outfile.txt'
cat("This is the first line", file = outfile, append = TRUE) #modified
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```

###Valid Color Names
```{r}
# your is_color() function
is_color <- function(col) {
  if (col %in% colors()) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}


# test it:
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
```

```{r}
colplot <- function(col) {
  if (is_color(col)) {
    plot(x = runif(n = 10, min = 0, max = 5), y = runif(n = 10, min = 0, max = 10), main = paste("Testing color", col), xlab = "x", ylab = "y", col = col)
  } else {
    stop(paste("invalid color", col))
  }
}
```

```{r, error=T}
# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')
```

