---
title: "lab10-yvonne-zhou"
author: "Yvonne Zhou"
date: "4/11/2019"
output: html_document
---

```{r}
library(ggplot2)
```

#A less basic probability problem
```{r}
box1 = c("blue", "blue", "red")
box2 = c("blue", "blue", "red", "red", "red", "white")
```

```{r}
results = c()
for (i in 1:1000) {
  if (runif(1) > 0.5) {
    add = sample(box1, size = 4, replace = TRUE)
  } else {
    add = sample(box2, size = 4, replace = FALSE)
  }
  results = append(results, add)
}
drawn_balls = matrix(data = results, nrow = 1000, ncol = 4, byrow = TRUE)
head(drawn_balls)
#results
```

```{r}
proportion = function(n) {
  if (n == 0) {
    return(c(1, 0, 0, 0, 0))
  } else {
    zero_blue = 0
    one_blue = 0
    two_blue = 0
    three_blue = 0
    four_blue = 0
    for (i in 1:n) {
      one_sample = drawn_balls[i,]
      num = 0
      for (j in 1:4) {
        if (one_sample[j] == "blue") {
          num = num + 1
        }
      }
      if (num == 0) {
        zero_blue = zero_blue + 1
      } else if (num == 1) {
        one_blue = one_blue + 1
      } else if (num == 2) {
        two_blue = two_blue + 1
      } else if (num == 3) {
        three_blue = three_blue + 1
      } else if (num == 4) {
        four_blue = four_blue + 1
      }
    }
    
    zero_blue = zero_blue / n
    one_blue = one_blue / n
    two_blue = two_blue / n
    three_blue = three_blue / n
    four_blue = four_blue / n
    
    return(c(zero_blue, one_blue, two_blue, three_blue, four_blue))
  }
}

#proportion(1)
```

```{r}
balls = data.frame()
for (i in 0:1000) {
  balls = rbind(balls, proportion(i))
}
names(balls) = c("zero", "one", "two", "three", "four")
balls$reps = 0:1000
head(balls)
```

```{r}
ggplot(data = balls) +
  geom_line(aes(x = reps, y = zero, color = "#F08080")) +
  geom_line(aes(x = reps, y = one, color = "#BDB76B")) +
  geom_line(aes(x = reps, y = two, color = "#7FFFD4")) + 
  geom_line(aes(x = reps, y = three, color = "#00BFFF")) + 
  geom_line(aes(x = reps, y = four, color = "#FF00FF")) +
  ylab("freqs") +
  labs(colour = "number") +
  scale_color_manual(labels = c("0", "1", "2", "3", "4"), values = c("#F08080", "#BDB76B", "#7FFFD4", "#00BFFF", "#FF00FF")) +
  ggtitle("Relative frequencies of number of blue balls")
```

