workout01-yvonne-zhou
================
Yvonne Zhou
3/10/2019

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

Iguodala, Green, Durant, Thompson and Curry in 2016
===================================================

### Introduction

The 2016 regular season has passed, but the competition during that season has never passed. In the season, as one of the best teams, Golden State Warriors has shown its outstanding strength and its players has also presented their amazing techniques. With this report, we are trying to know the value of the top five most valuable players, Andre Iguodala, Graymond Green, Kevin Durant, Klay Thompson and Stephen Curry, by analyzing their field goal percentages in the 2016 season. So who are the player who is really good at shooting?

In the 2016 regular season, players Andre Iguodala, Graymond Green, Kevin Durant, Klay Thompson and Stephen Curry contribute a lot for the team Golden State Warriors. During the whole year, in nearly every places on the court, they have scored points.

### Motivation

Why Andre Iguodala, Graymond Green, Kevin Durant, Klay Thompson and Stephen Curry are the top five most valuable players in Golden State Warriors? Why are they valuable? Among them, who are the player who goals the most? Do they deserve their fame?

### Background

##### 2009–present: The Stephen Curry era

The Warriors chose future superstar point guard Stephen Curry of Davidson College with the seventh overall pick in the 2009 NBA draft. During the 2009 off-season, Warrior ownership declined to renew the contract of general manager Chris Mullin. Larry Riley, Nelson's longtime assistant coach, was promoted in his place; Riley drafted Curry and traded Jamal Crawford to the Atlanta Hawks for Acie Law and Speedy Claxton. (CR. Wikipedia)

### Data

<img src="../images/gsw-shot-charts.png" width="80%" style="display: block; margin: auto;" />

##### Field Goal Percentage

| name           |  total|  made|  perc\_made|
|:---------------|------:|-----:|-----------:|
| Kevin Durant   |    915|   495|   0.5409836|
| Andre Iguodala |    371|   192|   0.5175202|
| Klay Thompson  |   1220|   575|   0.4713115|
| Stephen Curry  |   1250|   584|   0.4672000|
| Graymond Green |    578|   245|   0.4238754|

##### 2 Point Goal Percentage

| name           |  total|  made|  perc\_made|
|:---------------|------:|-----:|-----------:|
| Andre Iguodala |    210|   134|   0.6380952|
| Kevin Durant   |    643|   390|   0.6065319|
| Stephen Curry  |    563|   304|   0.5399645|
| Klay Thompson  |    640|   329|   0.5140625|
| Graymond Green |    346|   171|   0.4942197|

##### 3 Point Goal Percentage

| name           |  total|  made|  perc\_made|
|:---------------|------:|-----:|-----------:|
| Klay Thompson  |    580|   246|   0.4241379|
| Stephen Curry  |    687|   280|   0.4075691|
| Kevin Durant   |    272|   105|   0.3860294|
| Andre Iguodala |    161|    58|   0.3602484|
| Graymond Green |    232|    74|   0.3189655|

### Analysis

Kevin Durant is the player who has the highest field goal percentage. He surpassed the four others by a percentage of nearly 54.1%.

Andre Iguodala is the player who has the highest 2 point goal percentage. He surpassed the four others by a percentage of nearly 63.8%.

Klay Thompson is the player who has the highest 3 point goal percentage. He surpassed the four others by a percentage of nearly 42.4%.

Stephen Curry is the player who made the largest amount of shoots and also the player who goals the largest amount.

### Discussion

From the data and analysis above, Kevin Durant is not the player who has the highest 2 point goal percentage and 3 point goal percentage, but his field goal percentage is the highest among the five players, showing that he is the kind of player who is stable at both the 2 point and 3 point goals comparing to the other four players. Andre Iguodala's two goal percentage, which is the highest among the five, showing that he is really a valuable player as it is quite outstanding for players to get a 63.8% of goal percentage. This is also true for Thompson. Three points goals, especially in the fiercing competitive field, is really hard to get. In this kind of situation, he can still reaches 42.4% of goals, which could be said as something magnificent. And Stephen Curry, as the player who made the largest amount of shoots and also the player who goals the largest amount, perfectly shows his skills and techniques in his every trial of goal.

### Conclusions

From the data and following analysis, it is not hard to see that Andre Iguodala, Klay Thompson, Kevin Durant and Stephen Curry are really four outstanding players in NBA. Graymond Green, since not in the list, is not that strong as the other four players. But, the data is only about the percentage of goaling of these five players, and goal percentages are only a part of the process of getting the players' value. So, we can see that Andre Iguodala, Klay Thompson, Kevin Durant and Stephen Curry are all good at goaling and they are all trying hard and showing their skills in the 2016 season, and they have all helped the Golden State Warriors to be the today's Golden State Warriors.

### References

"Golden State Warriors". *Wikipedia.* 10 March 2019. Retrieved March 13, 2019.
